to Dolly

diff --git a/gitops/manifests/polaris/1-manifest/batch_v1-job-polaris-polaris-catalog-creator.yaml b/gitops/manifests/polaris/1-manifest/batch_v1-job-polaris-polaris-catalog-creator.yaml
--- a/gitops/manifests/polaris/1-manifest/batch_v1-job-polaris-polaris-catalog-creator.yaml
+++ b/gitops/manifests/polaris/1-manifest/batch_v1-job-polaris-polaris-catalog-creator.yaml
@@ -18,60 +18,60 @@ spec:
           apk add --no-cache jq curl
 
           token=$(curl -s http://polaris:8181/api/catalog/v1/oauth/tokens \
-            --user ${CLIENT_ID}:${CLIENT_SECRET} \
-            -d grant_type=client_credentials \
-            -d scope=PRINCIPAL_ROLE:ALL | sed -n 's/.*\"access_token\":\"\([^\"]*\)\".*/\1/p')
+          --user ${CLIENT_ID}:${CLIENT_SECRET} \
+          -d grant_type=client_credentials \
+          -d scope=PRINCIPAL_ROLE:ALL | sed -n 's/.*\"access_token\":\"\([^\"]*\)\".*/\1/p')
 
           if [ -z "${token}" ]; then
-            echo "Failed to obtain access token."
-            exit 1
+          echo "Failed to obtain access token."
+          exit 1
           fi
           echo
           echo "Obtained access token: ${token}"
 
           STORAGE_TYPE="FILE"
           if [ -z "${STORAGE_LOCATION}" ]; then
-              echo "STORAGE_LOCATION is not set, using FILE storage type"
-              STORAGE_LOCATION="file:///var/tmp/quickstart_catalog/"
+          echo "STORAGE_LOCATION is not set, using FILE storage type"
+          STORAGE_LOCATION="file:///var/tmp/quickstart_catalog/"
           else
-              echo "STORAGE_LOCATION is set to '${STORAGE_LOCATION}'"
-              if [[ "${STORAGE_LOCATION}" == s3* ]]; then
-                  STORAGE_TYPE="S3"
-              fi
-              echo "Using StorageType: $STORAGE_TYPE"
+          echo "STORAGE_LOCATION is set to '${STORAGE_LOCATION}'"
+          if [[ "${STORAGE_LOCATION}" == s3* ]]; then
+          STORAGE_TYPE="S3"
+          fi
+          echo "Using StorageType: $STORAGE_TYPE"
           fi
 
           STORAGE_CONFIG_INFO="{\"storageType\": \"$STORAGE_TYPE\", \"allowedLocations\": [\"$STORAGE_LOCATION\"]}"
           if [[ "$STORAGE_TYPE" == "S3" ]]; then
-              if [ -n "${AWS_ROLE_ARN}" ]; then
-                  STORAGE_CONFIG_INFO=$(echo "$STORAGE_CONFIG_INFO" | jq --arg roleArn "$AWS_ROLE_ARN" '. + {roleArn: $roleArn}')
-              else
-                  echo "Warning: AWS_ROLE_ARN not set for S3 storage"
-              fi
+          if [ -n "${AWS_ROLE_ARN}" ]; then
+          STORAGE_CONFIG_INFO=$(echo "$STORAGE_CONFIG_INFO" | jq --arg roleArn "$AWS_ROLE_ARN" '. + {roleArn: $roleArn}')
+          else
+          echo "Warning: AWS_ROLE_ARN not set for S3 storage"
+          fi
           fi
 
           echo
           echo Creating a catalog named quickstart_catalog...
 
           PAYLOAD='{
-            "catalog": {
-              "name": "quickstart_catalog",
-              "type": "INTERNAL",
-              "readOnly": false,
-              "properties": {
-                "default-base-location": "'"$STORAGE_LOCATION"'"
-              },
-              "storageConfigInfo": '$STORAGE_CONFIG_INFO'
-            }
+          "catalog": {
+          "name": "quickstart_catalog",
+          "type": "INTERNAL",
+          "readOnly": false,
+          "properties": {
+          "default-base-location": "'"$STORAGE_LOCATION"'"
+          },
+          "storageConfigInfo": '$STORAGE_CONFIG_INFO'
+          }
           }'
 
           echo $PAYLOAD
 
           curl -s -H "Authorization: Bearer ${token}" \
-             -H 'Accept: application/json' \
-             -H 'Content-Type: application/json' \
-             http://polaris:8181/api/management/v1/catalogs \
-             -d "$PAYLOAD" -v
+          -H 'Accept: application/json' \
+          -H 'Content-Type: application/json' \
+          http://polaris:8181/api/management/v1/catalogs \
+          -d "$PAYLOAD" -v
 
           echo
           echo Done.
@@ -96,21 +96,13 @@ spec:
       - command:
         - sh
         - -c
-        - |-
-          max_attempts=15
-          attempt=1
-          while [ $attempt -le $max_attempts ]; do
-            echo "Attempt $attempt: Checking Polaris API health..."
-            if curl --fail --silent --output /dev/null http://polaris-mgmt:8182/q/health/live; then
-              echo "Polaris API is healthy!"
-              exit 0
-            fi
-            echo "Waiting for Polaris API... (attempt $attempt of $max_attempts)"
-            attempt=$((attempt + 1))
-            sleep 5
-          done
-          echo "Polaris API did not become healthy after $max_attempts attempts."
-          exit 1
+        - "max_attempts=15\nattempt=1\nwhile [ $attempt -le $max_attempts ]; do\n
+          \ echo \"Attempt $attempt: Checking Polaris API health...\"\n  if curl --fail
+          --silent --output /dev/null http://polaris-mgmt:8182/q/health/live; then\n
+          \   echo \"Polaris API is healthy!\"\n    exit 0\n  fi\n  echo \"Waiting
+          for Polaris API... (attempt $attempt of $max_attempts)\"\n  attempt=$((attempt
+          + 1))\n  sleep 5\ndone\necho \"Polaris API did not become healthy after
+          $max_attempts attempts.\"\nexit 1      "
         image: alpine/curl
         name: wait-for-polaris-api
       restartPolicy: OnFailure
