resolve comment

diff --git a/gitops/manifests/polaris/1-manifest/batch_v1-job-polaris-polaris-catalog-creator.yaml b/gitops/manifests/polaris/1-manifest/batch_v1-job-polaris-polaris-catalog-creator.yaml
--- a/gitops/manifests/polaris/1-manifest/batch_v1-job-polaris-polaris-catalog-creator.yaml
+++ b/gitops/manifests/polaris/1-manifest/batch_v1-job-polaris-polaris-catalog-creator.yaml
@@ -21,58 +21,56 @@ spec:
               --user ${CLIENT_ID}:${CLIENT_SECRET} \
               -d grant_type=client_credentials \
               -d scope=PRINCIPAL_ROLE:ALL | sed -n 's/.*\"access_token\":\"\([^\"]*\)\".*/\1/p')
-              if [ -z "${token}" ]; then
 
-          echo "Failed to obtain access token."
-          exit 1
+          if [ -z "${token}" ]; then
+              echo "Failed to obtain access token."
+              exit 1
           fi
+
           echo
           echo "Obtained access token: ${token}"
 
-          STORAGE_TYPE="FILE"
-          if [ -z "${STORAGE_LOCATION}" ]; then
-          echo "STORAGE_LOCATION is not set, using FILE storage type"
-          STORAGE_LOCATION="file:///var/tmp/quickstart_catalog/"
+          if [[ "$STORAGE_LOCATION" == s3* ]]; then
+              STORAGE_TYPE="S3"
           else
-          echo "STORAGE_LOCATION is set to '${STORAGE_LOCATION}'"
-          if [[ "${STORAGE_LOCATION}" == s3* ]]; then
-          STORAGE_TYPE="S3"
+              echo "Error: Only S3 storage is supported. STORAGE_LOCATION must start with 's3'."
+              exit 1
           fi
+
           echo "Using StorageType: $STORAGE_TYPE"
-          fi
 
           STORAGE_CONFIG_INFO="{\"storageType\": \"$STORAGE_TYPE\", \"allowedLocations\": [\"$STORAGE_LOCATION\"]}"
           if [[ "$STORAGE_TYPE" == "S3" ]]; then
-          if [ -n "${AWS_ROLE_ARN}" ]; then
-          STORAGE_CONFIG_INFO=$(echo "$STORAGE_CONFIG_INFO" | jq --arg roleArn "$AWS_ROLE_ARN" '. + {roleArn: $roleArn}')
-          else
-          echo "Warning: AWS_ROLE_ARN not set for S3 storage"
-          fi
+              if [ -n "${AWS_ROLE_ARN}" ]; then
+                  STORAGE_CONFIG_INFO=$(echo "$STORAGE_CONFIG_INFO" | jq --arg roleArn "$AWS_ROLE_ARN" '. + {roleArn: $roleArn}')
+              else
+                  echo "Warning: AWS_ROLE_ARN not set for S3 storage"
+              fi
           fi
 
           echo
           echo Creating a catalog named quickstart_catalog...
 
           PAYLOAD='{
-          "catalog": {
-          "name": "quickstart_catalog",
-          "type": "INTERNAL",
-          "readOnly": false,
-          "properties": {
-          "default-base-location": "'"$STORAGE_LOCATION"'"
-          },
-          "storageConfigInfo": '$STORAGE_CONFIG_INFO'
-          }
+              "catalog": {
+                  "name": "quickstart_catalog",
+                  "type": "INTERNAL",
+                  "readOnly": false,
+                  "properties": {
+                  "default-base-location": "'"$STORAGE_LOCATION"'"
+                  },
+                  "storageConfigInfo": '$STORAGE_CONFIG_INFO'
+              }
           }'
 
           echo $PAYLOAD
-          curl -s -H "Authorization: Bearer ${token}" \
-          -H 'Accept: application/json' \
-          -H 'Content-Type: application/json' \
-          http://polaris:8181/api/management/v1/catalogs \
-          -d "$PAYLOAD" -v
 
-          echo
+          curl -s -H "Authorization: Bearer ${token}" \
+              -H 'Accept: application/json' \
+              -H 'Content-Type: application/json' \
+              http://polaris:8181/api/management/v1/catalogs \
+              -d "$PAYLOAD" -v
+
           echo Done.
         env:
         - name: STORAGE_LOCATION
